using NUnit.Framework;

namespace Rocks.Tests.Generators;

public static class ConstructorGeneratorTests
{
	[Test]
	public static async Task GenerateWhenNoAccessibleConstructorsExistAsync()
	{
		var code =
			"""
			using Rocks;

			[assembly: RockCreate<Constructable>]

			#nullable enable

			public class Constructable
			{
				private Constructable() { }

				public virtual object GetValue() => new();			
			}
			""";

		await TestAssistants.RunGeneratorAsync<RockAttributeGenerator>(code,
			[],
			[]);
	}

	[Test]
	public static async Task GenerateWhenOnlyConstructorsIsObsoleteAsync()
	{
		var code =
			"""
			using Rocks;
			using System;

			[assembly: RockCreate<Constructable>]

			#nullable enable

			public class Constructable
			{
				[Obsolete("Old", true)]
				public Constructable() { }

				public virtual object GetValue() => new();			
			}
			""";

		await TestAssistants.RunGeneratorAsync<RockAttributeGenerator>(code,
			[],
			[]);
	}

	[Test]
	public static async Task GenerateWhenTypeArgumentsCreateDuplicateConstructorsAsync()
	{
		var code =
			"""
			using Rocks;

			[assembly: RockCreate<AnyOf<object, object>>]

			#nullable enable

			public class AnyOf<T1, T2>
			{
				public AnyOf(T1 value) { }

				public AnyOf(T2 value) { }

				public virtual object GetValue() => new();			
			}
			""";

		await TestAssistants.RunGeneratorAsync<RockAttributeGenerator>(code,
			[],
			[]);
	}

	[Test]
	public static async Task GenerateWhenTypeArgumentsDoNotCreateDuplicateConstructorsAsync()
	{
		var code =
			"""
			using Rocks;

			[assembly: RockCreate<AnyOf<string, int>>]

			#nullable enable

			public class AnyOf<T1, T2>
			{
				public AnyOf(T1 value) { }

				public AnyOf(T2 value) { }

				public virtual object GetValue() => new();			
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class AnyOfOfstring_intCreateExpectations
				: global::Rocks.Expectations
			{
				internal sealed class Handler0
					: global::Rocks.Handler<global::System.Func<object?, bool>, bool>
				{
					public global::Rocks.Argument<object?> @obj { get; set; }
				}
				private global::Rocks.Handlers<global::AnyOfOfstring_intCreateExpectations.Handler0>? @handlers0;
				internal sealed class Handler1
					: global::Rocks.Handler<global::System.Func<int>, int>
				{ }
				private global::Rocks.Handlers<global::AnyOfOfstring_intCreateExpectations.Handler1>? @handlers1;
				internal sealed class Handler2
					: global::Rocks.Handler<global::System.Func<string?>, string?>
				{ }
				private global::Rocks.Handlers<global::AnyOfOfstring_intCreateExpectations.Handler2>? @handlers2;
				internal sealed class Handler3
					: global::Rocks.Handler<global::System.Func<object>, object>
				{ }
				private global::Rocks.Handlers<global::AnyOfOfstring_intCreateExpectations.Handler3>? @handlers3;
				
				public override void Verify()
				{
					if (this.WasInstanceInvoked)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(this.Verify(this.handlers0, 0)); }
						if (this.handlers1 is not null) { failures.AddRange(this.Verify(this.handlers1, 1)); }
						if (this.handlers2 is not null) { failures.AddRange(this.Verify(this.handlers2, 2)); }
						if (this.handlers3 is not null) { failures.AddRange(this.Verify(this.handlers3, 3)); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::AnyOf<string, int>
				{
					public Mock(global::AnyOfOfstring_intCreateExpectations @expectations, string @value)
						: base(@value)
					{
						this.Expectations = @expectations;
					}
					public Mock(global::AnyOfOfstring_intCreateExpectations @expectations, int @value)
						: base(@value)
					{
						this.Expectations = @expectations;
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public override bool Equals(object? @obj)
					{
						if (this.Expectations.handlers0 is not null)
						{
							foreach (var @handler in this.Expectations.handlers0)
							{
								if (@handler.@obj.IsValid(@obj!))
								{
									@handler.CallCount++;
									var @result = @handler.Callback is not null ?
										@handler.Callback(@obj!) : @handler.ReturnValue;
									return @result!;
								}
							}
							
							throw new global::Rocks.Exceptions.ExpectationException($"No handlers match for {this.GetType().GetMemberDescription(0)}");
						}
						else
						{
							return base.Equals(obj: @obj!);
						}
					}
					
					[global::Rocks.MemberIdentifier(1)]
					public override int GetHashCode()
					{
						if (this.Expectations.handlers1 is not null)
						{
							var @handler = this.Expectations.handlers1.First;
							@handler.CallCount++;
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.GetHashCode();
						}
					}
					
					[global::Rocks.MemberIdentifier(2)]
					public override string? ToString()
					{
						if (this.Expectations.handlers2 is not null)
						{
							var @handler = this.Expectations.handlers2.First;
							@handler.CallCount++;
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.ToString();
						}
					}
					
					[global::Rocks.MemberIdentifier(3)]
					public override object GetValue()
					{
						if (this.Expectations.handlers3 is not null)
						{
							var @handler = this.Expectations.handlers3.First;
							@handler.CallCount++;
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.GetValue();
						}
					}
					
					private global::AnyOfOfstring_intCreateExpectations Expectations { get; }
				}
				
				internal sealed class MethodExpectations
				{
					internal MethodExpectations(global::AnyOfOfstring_intCreateExpectations expectations) =>
						this.Expectations = expectations;
					
					internal global::AnyOfOfstring_intCreateExpectations.Adornments.AdornmentsForHandler0 Equals(global::Rocks.Argument<object?> @obj)
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.Expectations.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@obj);
						
						var @handler = new global::AnyOfOfstring_intCreateExpectations.Handler0
						{
							@obj = @obj,
						};
						
						if (this.Expectations.handlers0 is null) { this.Expectations.handlers0 = new(@handler); }
						else { this.Expectations.handlers0.Add(@handler); }
						return new(@handler);
					}
					
					internal new global::AnyOfOfstring_intCreateExpectations.Adornments.AdornmentsForHandler1 GetHashCode()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.Expectations.WasInstanceInvoked);
						var handler = new global::AnyOfOfstring_intCreateExpectations.Handler1();
						if (this.Expectations.handlers1 is null) { this.Expectations.handlers1 = new(handler); }
						else { this.Expectations.handlers1.Add(handler); }
						return new(handler);
					}
					
					internal new global::AnyOfOfstring_intCreateExpectations.Adornments.AdornmentsForHandler2 ToString()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.Expectations.WasInstanceInvoked);
						var handler = new global::AnyOfOfstring_intCreateExpectations.Handler2();
						if (this.Expectations.handlers2 is null) { this.Expectations.handlers2 = new(handler); }
						else { this.Expectations.handlers2.Add(handler); }
						return new(handler);
					}
					
					internal global::AnyOfOfstring_intCreateExpectations.Adornments.AdornmentsForHandler3 GetValue()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.Expectations.WasInstanceInvoked);
						var handler = new global::AnyOfOfstring_intCreateExpectations.Handler3();
						if (this.Expectations.handlers3 is null) { this.Expectations.handlers3 = new(handler); }
						else { this.Expectations.handlers3.Add(handler); }
						return new(handler);
					}
					
					private global::AnyOfOfstring_intCreateExpectations Expectations { get; }
				}
				
				internal global::AnyOfOfstring_intCreateExpectations.MethodExpectations Methods { get; }
				
				internal AnyOfOfstring_intCreateExpectations() =>
					(this.Methods) = (new(this));
				
				internal global::AnyOf<string, int> Instance(string @value)
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						var @mock = new Mock(this, @value);
						this.MockType = @mock.GetType();
						return @mock;
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				internal global::AnyOf<string, int> Instance(int @value)
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						var @mock = new Mock(this, @value);
						this.MockType = @mock.GetType();
						return @mock;
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					public interface IAdornmentsForAnyOfOfstring_int<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForAnyOfOfstring_int<TAdornments>
					{ }
					
					public sealed class AdornmentsForHandler0
						: global::Rocks.Adornments<AdornmentsForHandler0, global::AnyOfOfstring_intCreateExpectations.Handler0, global::System.Func<object?, bool>, bool>, IAdornmentsForAnyOfOfstring_int<AdornmentsForHandler0>
					{
						public AdornmentsForHandler0(global::AnyOfOfstring_intCreateExpectations.Handler0 handler)
							: base(handler) { }
					}
					public sealed class AdornmentsForHandler1
						: global::Rocks.Adornments<AdornmentsForHandler1, global::AnyOfOfstring_intCreateExpectations.Handler1, global::System.Func<int>, int>, IAdornmentsForAnyOfOfstring_int<AdornmentsForHandler1>
					{
						public AdornmentsForHandler1(global::AnyOfOfstring_intCreateExpectations.Handler1 handler)
							: base(handler) { }
					}
					public sealed class AdornmentsForHandler2
						: global::Rocks.Adornments<AdornmentsForHandler2, global::AnyOfOfstring_intCreateExpectations.Handler2, global::System.Func<string?>, string?>, IAdornmentsForAnyOfOfstring_int<AdornmentsForHandler2>
					{
						public AdornmentsForHandler2(global::AnyOfOfstring_intCreateExpectations.Handler2 handler)
							: base(handler) { }
					}
					public sealed class AdornmentsForHandler3
						: global::Rocks.Adornments<AdornmentsForHandler3, global::AnyOfOfstring_intCreateExpectations.Handler3, global::System.Func<object>, object>, IAdornmentsForAnyOfOfstring_int<AdornmentsForHandler3>
					{
						public AdornmentsForHandler3(global::AnyOfOfstring_intCreateExpectations.Handler3 handler)
							: base(handler) { }
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			""";

		await TestAssistants.RunGeneratorAsync<RockAttributeGenerator>(code,
			[(typeof(RockAttributeGenerator), "AnyOfstring, int_Rock_Create.g.cs", generatedCode)],
			[]);
	}
}