namespace Rocks.Runtime;

/// <summary>
/// Defines the interface to raise an event
/// on a mock.
/// </summary>
/// <remarks>
/// This type is designed to be used from code generated by Rocks,
/// and is not intended for general use. Please refrain from
/// referencing it for any other purposes, as its implementation may change.
/// </remarks>
public interface IRaiseEvents
{
	/// <summary>
	/// Raises the specified event.
	/// </summary>
	/// <param name="eventName">The name of the event.</param>
	/// <param name="args">The arguments for the event.</param>
	void Raise(string eventName, object args);
}