using Rocks.Runtime;

// This is an odd one, but all I'm doing
// is making sure that the analyzer is 
// working correctly. So, I create a type
// that I know the analyzer should create a diagnostic for,
// and then put a #pragma around it.
// Now, there is an informational diagnostic
// that will state if a #pragma is not needed (IDE0079),
// but...I can't make that a "warning" (and then an error),
// which would be nice because then it would tell me
// if the analyzer wasn't firing. At least
// I can't figure out how to do that. But this
// is sufficient for now.

#pragma warning disable ROCK1 // Cannot Mock Sealed Types
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AnalyzerTestTypes.AnalyzerTests), BuildType.Create)]
#pragma warning restore ROCK1 // Cannot Mock Sealed Types

[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassConstructorTestTypes.AbstractClassConstructor), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericEventsTestTypes.AbstractClassGenericEvents<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericIndexerTestTypes.AbstractClassGenericIndexer<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericIndexerTestTypes.AbstractClassGenericIndexerGetAndInit<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericMethodTestTypes.AbstractClassGenericMethod<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericPropertyTestTypes.AbstractClassGenericProperty<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericPropertyTestTypes.AbstractClassGenericPropertyGetAndInit<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerGetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerGetterInit), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerGetterSetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerSetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodReturnTestTypes.AbstractClassMethodReturn), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodReturnWithEventsTestTypes.AbstractClassMethodReturnWithEvents), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodVoidTestTypes.AbstractMethodVoidTests), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodVoidWithEventsTestTypes.AbstractClassMethodVoidWithEvents), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassPropertyTestTypes.AbstractClassProperty), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AllowNullTestTypes.Allow), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AllowNullTestTypes.IAllow), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ArgTestTypes.IHaveArgument), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AsynchronousTestTypes.AsyncEnumeration), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AsynchronousTestTypes.IAmAsynchronous), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AttributeTestTypes.ConventionDispatcher), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.AttributeTestTypes.NotNullIfNotCases), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassConstructorTestTypes.ClassConstructor), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassConstructorTestTypes.ClassConstructorWithSpecialParameters), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericEventsTestTypes.ClassGenericEvents<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericIndexerTestTypes.ClassGenericIndexer<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericIndexerTestTypes.ClassGenericIndexerGetAndInit<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericMethodTestTypes.ClassGenericMethod<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericPropertyTestTypes.ClassGenericProperty<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericPropertyTestTypes.ClassGenericPropertyGetAndInit<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerGetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerGetterInit), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerGetterSetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerInit), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerSetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodReturnTestTypes.ClassMethodReturn), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodReturnWithEventsTestTypes.ClassMethodReturnWithEvents), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodVoidTestTypes.MethodVoidTests), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodVoidWithEventsTestTypes.ClassMethodVoidWithEvents), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ClassPropertyTestTypes.ClassProperty), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ConstraintTestTypes.BaseForConstraintCase<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.DoesNotReturnTestTypes.UsesDoesNotReturn), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.EventTestTypes.IUseNotEventArgs), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ExpectationExceptionTestTypes.ISetAfterMock), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ExplicitInterfaceImplementationTestTypes.IExplicitInterfaceImplementation), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ExplicitInterfaceImplementationTestTypes.IIterable<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.GenericTestTypes.GenericContainer), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.GenericTestTypes.IGenericContainer), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericEventsTestTypes.IInterfaceGenericEvents<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericIndexerTestTypes.IInterfaceGenericIndexer<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericIndexerTestTypes.IInterfaceGenericIndexerGetAndInit<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericMethodTestTypes.IInterfaceGenericMethod<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericMethodTestTypes.IRequest<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericPropertyTestTypes.IInterfaceGenericProperty<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericPropertyTestTypes.IInterfaceGenericPropertyGetAndInit<>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerGetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerGetterInit), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerGetterSetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerInit), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerSetter), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodReturnTestTypes.IInterfaceMethodReturn), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodReturnWithEventsTestTypes.IInterfaceMethodReturnWithEvents), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodVoidTestTypes.IInterfaceMethodVoid), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodVoidWithEventsTestTypes.IInterfaceMethodVoidWithEvents), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfacePropertyTestTypes.IInterfaceProperty), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceStaticVirtualTestTypes.IHaveStaticVirtuals), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveIn), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveLotsOfParameters), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveRefAndOut), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveRefReturn), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.MultipleRockCallsTestTypes.IMultipleRockCalls), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.NonPublicMemberTestTypes.HasProtectedMember), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.OpenGenericsTestTypes.IService<,>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.OptionalArgumentsTestTypes.NeedNullableAnnotation), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.OptionalArgumentsTestTypes.IHaveOptionalArguments), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.OptionalArgumentsTestTypes.IHaveOptionalStructDefaultArgument), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.ParamsTestTypes.IHaveParams), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.PointerTestTypes.IHavePointers), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.GenericTestTypes.ISourceUpdater<,>), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.PointerTestTypes.ISurface), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.RecordTestTypes.MyRecord), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IHaveInAndOutSpan), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IHaveScoped), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IHaveSpan), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IReturnSpan), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.RequiredInitPropertyTestTypes.Inits), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.RequiredInitPropertyTestTypes.Requireds), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.VerificationTestTypes.IData), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IIndexerPolygon), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IMethodPolygon), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IPropertyPolygon), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IndexerPolygon), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.MethodPolygon), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.PropertyPolygon), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.Referenced.IDoInternalStuff), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(Rocks.Analysis.IntegrationTests.Referenced.IDoPublicStuff), BuildType.Create | BuildType.Make)]
[assembly: Rock(typeof(System.Net.Http.HttpMessageHandler), BuildType.Create)]