// This is an odd one, but all I'm doing
// is making sure that the analyzer is 
// working correctly. So, I create a type
// that I know the analyzer should create a diagnostic for,
// and then put a #pragma around it.
// Now, there is an informational diagnostic
// that will state if a #pragma is not needed (IDE0079),
// but...I can't make that a "warning" (and then an error),
// which would be nice because then it would tell me
// if the analyzer wasn't firing. At least
// I can't figure out how to do that. But this
// is sufficient for now.

#pragma warning disable ROCK1 // Cannot Mock Sealed Types
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AnalyzerTestTypes.AnalyzerTests), Rocks.BuildType.Create)]
#pragma warning restore ROCK1 // Cannot Mock Sealed Types

[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassConstructorTestTypes.AbstractClassConstructor), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericEventsTestTypes.AbstractClassGenericEvents<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericIndexerTestTypes.AbstractClassGenericIndexer<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericIndexerTestTypes.AbstractClassGenericIndexerGetAndInit<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericMethodTestTypes.AbstractClassGenericMethod<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericPropertyTestTypes.AbstractClassGenericProperty<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassGenericPropertyTestTypes.AbstractClassGenericPropertyGetAndInit<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerGetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerGetterInit), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerGetterSetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassIndexerTestTypes.AbstractClassIndexerSetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodReturnTestTypes.AbstractClassMethodReturn), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodReturnWithEventsTestTypes.AbstractClassMethodReturnWithEvents), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodVoidTestTypes.AbstractMethodVoidTests), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassMethodVoidWithEventsTestTypes.AbstractClassMethodVoidWithEvents), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AbstractClassPropertyTestTypes.AbstractClassProperty), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AllowNullTestTypes.Allow), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AllowNullTestTypes.IAllow), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ArgTestTypes.IHaveArgument), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AsynchronousTestTypes.AsyncEnumeration), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AsynchronousTestTypes.IAmAsynchronous), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AttributeTestTypes.ConventionDispatcher), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AttributeTestTypes.ITense), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.AttributeTestTypes.NotNullIfNotCases), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassConstructorTestTypes.ClassConstructor), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassConstructorTestTypes.ClassConstructorWithSpecialParameters), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassConstructorTestTypes.ClassRequiredConstructor), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericEventsTestTypes.ClassGenericEvents<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericIndexerTestTypes.ClassGenericIndexer<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericIndexerTestTypes.ClassGenericIndexerGetAndInit<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericMethodTestTypes.ClassGenericMethod<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericPropertyTestTypes.ClassGenericProperty<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassGenericPropertyTestTypes.ClassGenericPropertyGetAndInit<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerGetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerGetterInit), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerGetterSetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerInit), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassIndexerTestTypes.ClassIndexerSetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodReturnTestTypes.ClassMethodReturn), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodReturnWithEventsTestTypes.ClassMethodReturnWithEvents), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodVoidTestTypes.MethodVoidTests), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassMethodVoidWithEventsTestTypes.ClassMethodVoidWithEvents), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ClassPropertyTestTypes.ClassProperty), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ConstraintTestTypes.BaseForConstraintCase<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.DoesNotReturnTestTypes.UsesDoesNotReturn), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.EventTestTypes.IUseNotEventArgs), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ExpectationExceptionTestTypes.ISetAfterMock), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ExplicitInterfaceImplementationTestTypes.IExplicitInterfaceImplementation), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ExplicitInterfaceImplementationTestTypes.IIterable<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.GenericTestTypes.GenericContainer), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.GenericTestTypes.IGenericContainer), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericEventsTestTypes.IInterfaceGenericEvents<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericIndexerTestTypes.IInterfaceGenericIndexer<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericIndexerTestTypes.IInterfaceGenericIndexerGetAndInit<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericMethodTestTypes.IInterfaceGenericMethod<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericMethodTestTypes.IRequest<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericPropertyTestTypes.IInterfaceGenericProperty<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceGenericPropertyTestTypes.IInterfaceGenericPropertyGetAndInit<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerGetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerGetterInit), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerGetterSetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerInit), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceIndexerTestTypes.IInterfaceIndexerSetter), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodReturnTestTypes.IInterfaceMethodReturn), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodReturnWithEventsTestTypes.IInterfaceMethodReturnWithEvents), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodVoidTestTypes.IInterfaceMethodVoid), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceMethodVoidWithEventsTestTypes.IInterfaceMethodVoidWithEvents), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfacePropertyTestTypes.IInterfaceProperty), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.InterfaceStaticVirtualTestTypes.IHaveStaticVirtuals), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveIn), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveLotsOfParameters), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveRefAndOut), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.MethodMemberTestTypes.IHaveRefReturn), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.MultipleRockCallsTestTypes.IMultipleRockCalls), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.NonPublicMemberTestTypes.HasProtectedMember), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.OpenGenericsTestTypes.IService<,>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.OptionalArgumentsTestTypes.NeedNullableAnnotation), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.OptionalArgumentsTestTypes.IHaveOptionalArguments), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.OptionalArgumentsTestTypes.IHaveOptionalStructDefaultArgument), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ParamsTestTypes.IHaveParams), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.PointerTestTypes.IHavePointers), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.GenericTestTypes.ISourceUpdater<,>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.PointerTestTypes.ISurface), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RecordTestTypes.MyRecord), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IHaveInAndOutSpan), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IHaveScoped), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IHaveSpan), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RefStructTestTypes.IReturnSpan), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RequiredInitPropertyTestTypes.Inits), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RequiredInitPropertyTestTypes.Requireds), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.VerificationTestTypes.IData), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IIndexerPolygon), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IMethodPolygon), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IPropertyPolygon), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.IndexerPolygon), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.MethodPolygon), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.VirtualsWithImplementationsTestTypes.PropertyPolygon), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.Referenced.IDoInternalStuff), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.Referenced.IDoPublicStuff), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(System.Net.Http.HttpMessageHandler), Rocks.BuildType.Create)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.ShimTestTypes.IAuditTrail<>), Rocks.BuildType.Create | Rocks.BuildType.Make)]
[assembly: Rocks.Rock(typeof(Rocks.Analysis.IntegrationTests.RockContextTestTypes.IContextural), Rocks.BuildType.Create | Rocks.BuildType.Make)]
