using NUnit.Framework;

namespace Rocks.Analysis.Tests.Generators;

public static class ProjectionGenericsAndPointersGeneratorTests
{
	[Test]
	public static async Task GenerateWithPointersAndGenericsAndUnmanagedConstraintAsync()
	{
		var code =
			"""
			using Rocks;

			[assembly: Rock(typeof(ISurface), BuildType.Create | BuildType.Make)]

			public interface ISurface
			{
				unsafe void Create<T>(T* allocator) where T : unmanaged;
			}
			""";

		var createGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal unsafe sealed class ISurfaceCreateExpectations
				: global::Rocks.Expectations
			{
				private readonly global::ISurfaceCreateExpectations.SetupsExpectations setups;
				
				internal sealed class SetupsExpectations
				{
					private readonly global::ISurfaceCreateExpectations parent;
				
					internal SetupsExpectations(global::ISurfaceCreateExpectations parent) =>
						this.parent = parent;
				
					internal global::ISurfaceCreateExpectations.Adornments.AdornmentsForHandler0<T> Create<T>(global::Rocks.Projections.PointerArgument<T> @allocator) where T : unmanaged
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@allocator);
						
						var @handler = new global::ISurfaceCreateExpectations.Handler0<T>
						{
							@allocator = @allocator,
						};
						
						if (this.parent.handlers0 is null) { this.parent.handlers0 = new(@handler); }
						else { this.parent.handlers0.Add(@handler); }
						return new(@handler);
					}
				}
				
				internal global::ISurfaceCreateExpectations.SetupsExpectations Setups => this.setups;
				
				internal sealed class Handler0<T>
					: global::Rocks.Handler<Handler0<T>.CallbackForHandler>
					where T : unmanaged
				{
					internal unsafe delegate void CallbackForHandler(T* @allocator);
					public global::Rocks.Projections.PointerArgument<T> @allocator { get; set; }
				}
				private global::Rocks.Handlers<global::Rocks.Handler>? @handlers0;
				
				public override void Verify()
				{
					if (!this.WasInstanceInvoked)
					{
						throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::ISurfaceCreateExpectations was never made."]);
					}
					else if (!this.WasExceptionThrown)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(this.Verify(this.handlers0, 0)); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::ISurface
				{
					public Mock(global::ISurfaceCreateExpectations @expectations)
					{
						this.Expectations = @expectations;
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public unsafe void Create<T>(T* @allocator)
						where T : unmanaged
					{
						if (this.Expectations.handlers0 is not null)
						{
							var @foundMatch = false;
							
							foreach (var @genericHandler in this.Expectations.handlers0)
							{
								if (@genericHandler is global::ISurfaceCreateExpectations.Handler0<T> @handler)
								{
									if (@handler.@allocator.IsValid(@allocator!))
									{
										@foundMatch = true;
										@handler.CallCount++;
										@handler.Callback?.Invoke(@allocator!);
										break;
									}
								}
							}
							
							if (!@foundMatch)
							{
								this.Expectations.WasExceptionThrown = true;
								throw new global::Rocks.Exceptions.ExpectationException(
									$"""
									No handlers match for {this.GetType().GetMemberDescription(0)}
										allocator: <Not formattable>
									""");
							}
						}
						else
						{
							this.Expectations.WasExceptionThrown = true;
							throw new global::Rocks.Exceptions.ExpectationException(
								$"""
								No handlers were found for {this.GetType().GetMemberDescription(0)}
									allocator: <Not formattable>
								""");
						}
					}
					
					private global::ISurfaceCreateExpectations Expectations { get; }
				}
				
				public ISurfaceCreateExpectations() => this.setups = new(this);
				
				internal global::ISurface Instance()
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						var @mock = new Mock(this);
						this.MockType = @mock.GetType();
						return @mock;
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					public interface IAdornmentsForISurface<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForISurface<TAdornments>
					{ }
					
					public sealed class AdornmentsForHandler0<T>
						: global::Rocks.Adornments<AdornmentsForHandler0<T>, global::ISurfaceCreateExpectations.Handler0<T>, global::ISurfaceCreateExpectations.Handler0<T>.CallbackForHandler>, IAdornmentsForISurface<AdornmentsForHandler0<T>> where T : unmanaged
					{
						public AdornmentsForHandler0(global::ISurfaceCreateExpectations.Handler0<T> handler)
							: base(handler) { }
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			"""";

		var makeGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class ISurfaceMakeExpectations
			{
				internal global::ISurface Instance()
				{
					return new Mock();
				}
				
				private sealed class Mock
					: global::ISurface
				{
					public Mock()
					{
					}
					
					public unsafe void Create<T>(T* @allocator)
						where T : unmanaged
					{
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			"""";

		var projectedCode =
			"""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			using System;
			using System.ComponentModel;
			
			#nullable enable
			
			namespace Rocks.Projections;
			
			internal unsafe delegate bool PointerArgumentEvaluation<T>(T* @value) where T : unmanaged;
			
			internal sealed unsafe class PointerArgument<T>
				: Argument
				where T : unmanaged
			{
				private readonly PointerArgumentEvaluation<T>? evaluation;
				private readonly T* value;
				private readonly ValidationState validation;
			
				internal PointerArgument() => this.validation = ValidationState.None;
			
				internal PointerArgument(T* @value)
				{
					this.value = @value;
					this.validation = ValidationState.Value;
				}
			
				internal PointerArgument(PointerArgumentEvaluation<T> @evaluation)
				{
					this.evaluation = @evaluation;
					this.validation = ValidationState.Evaluation;
				}
			
				public static implicit operator PointerArgument<T>(T* @value) => new(@value);
			
				public bool IsValid(T* @value) =>
					this.validation switch
					{
						ValidationState.None => true,
						ValidationState.Value => @value == this.value,
						ValidationState.Evaluation => this.evaluation!(@value),
						ValidationState.DefaultValue => throw new NotSupportedException("Cannot validate an argument value in the ValidationState.DefaultValue state."),
						_ => throw new InvalidEnumArgumentException($"Invalid value for validation: {this.validation}")
					};
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			""";

		await TestAssistants.RunGeneratorAsync<RockGenerator>(code,
			[
				("ISurface_Rock_Create.g.cs", createGeneratedCode),
				("ISurface_Rock_Make.g.cs", makeGeneratedCode),
				("Pointer_Projection.g.cs", projectedCode)
			],
			[]);
	}
}