using NUnit.Framework;

namespace Rocks.Analysis.Tests.Generators;

public static class VirtualsWithImplementationsGeneratorTests
{
	[Test]
	public static async Task GenerateForMethodWithParamsReturnsVoidAsync()
	{
		var code =
			"""
			using Rocks;
			using System;

			[assembly: Rock(typeof(MockTests.VoidMethodWithParams), BuildType.Create | BuildType.Make)]

			namespace MockTests
			{
				public class VoidMethodWithParams
				{
					public virtual void CallMe(params string[] values) { }
				}
			}
			
			""";

		var createGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			namespace MockTests;
			
			/// <summary>
			/// Contains mocking infrastructure code for <see cref="global::MockTests.VoidMethodWithParams"/>.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class VoidMethodWithParamsCreateExpectations
				: global::Rocks.Expectations
			{
				private readonly global::MockTests.VoidMethodWithParamsCreateExpectations.SetupsExpectations setups;
				
				/// <summary>
				/// Contains expectation setups for mockable members on <see cref="global::MockTests.VoidMethodWithParams"/>.
				/// </summary>
				internal sealed class SetupsExpectations
				{
					private readonly global::MockTests.VoidMethodWithParamsCreateExpectations parent;
				
					/// <summary>
					/// Creates a new <see cref="SetupsExpectations"/> instance.
					/// </summary>
					internal SetupsExpectations(global::MockTests.VoidMethodWithParamsCreateExpectations parent) =>
						this.parent = parent;
				
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.VoidMethodWithParams.Equals(Object)"/>.
					/// </summary>
					internal global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA Equals(global::Rocks.Argument<object?> @obj)
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@obj);
						
						var @handler = new global::MockTests.VoidMethodWithParamsCreateExpectations.Handler0
						{
							@obj = @obj,
						};
						
						this.parent.handlers0 ??= new(1);
						this.parent.handlers0.Add(@handler);
						return new(@handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.VoidMethodWithParams.GetHashCode()"/>.
					/// </summary>
					internal new global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE GetHashCode()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.VoidMethodWithParamsCreateExpectations.Handler1();
						this.parent.handlers1 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.VoidMethodWithParams.ToString()"/>.
					/// </summary>
					internal new global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.ToStringAdornments2D2816FE ToString()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.VoidMethodWithParamsCreateExpectations.Handler2();
						this.parent.handlers2 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.VoidMethodWithParams.CallMe()"/>.
					/// </summary>
					internal global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.CallMeAdornmentsED6F815B CallMe(global::Rocks.Argument<string[]> @values)
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@values);
						
						var @handler = new global::MockTests.VoidMethodWithParamsCreateExpectations.Handler3
						{
							@values = @values,
						};
						
						this.parent.handlers3 ??= new(1);
						this.parent.handlers3.Add(@handler);
						return new(@handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.VoidMethodWithParams.CallMe()"/>.
					/// </summary>
					internal global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.CallMeAdornmentsED6F815B CallMe(params string[] @values) =>
						this.CallMe(global::Rocks.Arg.Is(@values));
				}
				
				internal global::MockTests.VoidMethodWithParamsCreateExpectations.SetupsExpectations Setups => this.setups;
				
				internal sealed class Handler0
					: global::Rocks.Handler<global::System.Func<object?, bool>, bool>
				{
					internal global::Rocks.Argument<object?> @obj { get; set; }
				}
				private global::System.Collections.Generic.List<global::MockTests.VoidMethodWithParamsCreateExpectations.Handler0>? @handlers0;
				
				internal sealed class Handler1
					: global::Rocks.Handler<global::System.Func<int>, int>
				{ }
				private global::MockTests.VoidMethodWithParamsCreateExpectations.Handler1? @handlers1;
				
				internal sealed class Handler2
					: global::Rocks.Handler<global::System.Func<string?>, string?>
				{ }
				private global::MockTests.VoidMethodWithParamsCreateExpectations.Handler2? @handlers2;
				
				internal sealed class Handler3
					: global::Rocks.Handler<global::System.Action<string[]>>
				{
					internal global::Rocks.Argument<string[]> @values { get; set; }
				}
				private global::System.Collections.Generic.List<global::MockTests.VoidMethodWithParamsCreateExpectations.Handler3>? @handlers3;
				
				/// <summary>
				/// Verifies expectations set for the <see cref="global::MockTests.VoidMethodWithParams"/>-based mock.
				/// </summary>
				public override void Verify()
				{
					if (!this.WasInstanceInvoked)
					{
						throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::MockTests.VoidMethodWithParamsCreateExpectations was never made."]);
					}
					else if (!this.WasExceptionThrown)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(global::Rocks.Expectations.Verify(this.handlers0, 0, typeof(Mock))); }
						if (this.handlers1 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers1], 1, typeof(Mock))); }
						if (this.handlers2 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers2], 2, typeof(Mock))); }
						if (this.handlers3 is not null) { failures.AddRange(global::Rocks.Expectations.Verify(this.handlers3, 3, typeof(Mock))); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::MockTests.VoidMethodWithParams
				{
					public Mock(global::MockTests.VoidMethodWithParamsCreateExpectations @expectations)
					{
						this.Expectations = @expectations;
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public override bool Equals(object? @obj)
					{
						if (this.Expectations.handlers0 is not null)
						{
							foreach (var @handler in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Expectations.handlers0))
							{
								if (@handler.@obj.IsValid(@obj!))
								{
									@handler.CallCount++;
									if (@handler.Exception is not null) { throw @handler.Exception; }
									var @result = @handler.Callback is not null ?
										@handler.Callback(@obj!) : @handler.ReturnValue;
									return @result!;
								}
							}
							
							this.Expectations.WasExceptionThrown = true;
							throw new global::Rocks.Exceptions.ExpectationException(
								$"""
								No handlers match for {typeof(Mock).GetMemberDescription(0)}
									obj: {@obj.FormatValue()}
								""");
						}
						else
						{
							return base.Equals(@obj: @obj!);
						}
					}
					
					[global::Rocks.MemberIdentifier(1)]
					public override int GetHashCode()
					{
						if (this.Expectations.handlers1 is not null)
						{
							var @handler = this.Expectations.handlers1;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.GetHashCode();
						}
					}
					
					[global::Rocks.MemberIdentifier(2)]
					public override string? ToString()
					{
						if (this.Expectations.handlers2 is not null)
						{
							var @handler = this.Expectations.handlers2;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.ToString();
						}
					}
					
					[global::Rocks.MemberIdentifier(3)]
					public override void CallMe(params string[] @values)
					{
						if (this.Expectations.handlers3 is not null)
						{
							var @foundMatch = false;
							
							foreach (var @handler in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Expectations.handlers3))
							{
								if (@handler.@values.IsValid(@values!))
								{
									@foundMatch = true;
									@handler.CallCount++;
									if (@handler.Exception is not null) { throw @handler.Exception; }
									@handler.Callback?.Invoke(@values!);
									break;
								}
							}
							
							if (!@foundMatch)
							{
								this.Expectations.WasExceptionThrown = true;
								throw new global::Rocks.Exceptions.ExpectationException(
									$"""
									No handlers match for {typeof(Mock).GetMemberDescription(3)}
										values: {@values.FormatValue()}
									""");
							}
						}
						else
						{
							base.CallMe(@values: @values!);
						}
					}
					
					private global::MockTests.VoidMethodWithParamsCreateExpectations Expectations { get; }
				}
				
				public VoidMethodWithParamsCreateExpectations() => this.setups = new(this);
				
				/// <summary>
				/// Creates a new instance of a <see cref="global::MockTests.VoidMethodWithParams" />-based mock.
				/// </summary>
				/// <exception cref="global::Rocks.Exceptions.NewMockInstanceException">Thrown if a mock instance has already been created.</exception>
				internal global::MockTests.VoidMethodWithParams Instance()
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						return new Mock(this);
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					internal interface IAdornmentsForVoidMethodWithParams<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForVoidMethodWithParams<TAdornments>
					{ }
					
					internal sealed class EqualsAdornmentsE60CFEEA
						: global::Rocks.Adornments<EqualsAdornmentsE60CFEEA, global::MockTests.VoidMethodWithParamsCreateExpectations.Handler0, global::System.Func<object?, bool>, bool>, IAdornmentsForVoidMethodWithParams<EqualsAdornmentsE60CFEEA>
					{
						internal EqualsAdornmentsE60CFEEA(global::MockTests.VoidMethodWithParamsCreateExpectations.Handler0 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class GetHashCodeAdornments2D2816FE
						: global::Rocks.Adornments<GetHashCodeAdornments2D2816FE, global::MockTests.VoidMethodWithParamsCreateExpectations.Handler1, global::System.Func<int>, int>, IAdornmentsForVoidMethodWithParams<GetHashCodeAdornments2D2816FE>
					{
						internal GetHashCodeAdornments2D2816FE(global::MockTests.VoidMethodWithParamsCreateExpectations.Handler1 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class ToStringAdornments2D2816FE
						: global::Rocks.Adornments<ToStringAdornments2D2816FE, global::MockTests.VoidMethodWithParamsCreateExpectations.Handler2, global::System.Func<string?>, string?>, IAdornmentsForVoidMethodWithParams<ToStringAdornments2D2816FE>
					{
						internal ToStringAdornments2D2816FE(global::MockTests.VoidMethodWithParamsCreateExpectations.Handler2 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class CallMeAdornmentsED6F815B
						: global::Rocks.Adornments<CallMeAdornmentsED6F815B, global::MockTests.VoidMethodWithParamsCreateExpectations.Handler3, global::System.Action<string[]>>, IAdornmentsForVoidMethodWithParams<CallMeAdornmentsED6F815B>
					{
						internal CallMeAdornmentsED6F815B(global::MockTests.VoidMethodWithParamsCreateExpectations.Handler3 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
				}
				
				internal void Remove(global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA adornments)
				{
					adornments.Remove(this.@handlers0);
					if (this.@handlers0?.Count == 0) { this.@handlers0 = null; }
				}
				
				internal void Remove(global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE adornments) =>
					this.@handlers1 = null;
				
				internal void Remove(global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.ToStringAdornments2D2816FE adornments) =>
					this.@handlers2 = null;
				
				internal void Remove(global::MockTests.VoidMethodWithParamsCreateExpectations.Adornments.CallMeAdornmentsED6F815B adornments)
				{
					adornments.Remove(this.@handlers3);
					if (this.@handlers3?.Count == 0) { this.@handlers3 = null; }
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			"""";

		var makeGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			namespace MockTests
			{
				/// <summary>
				/// Contains code to create a "simple" definition of <see cref="global::MockTests.VoidMethodWithParams"/>.
				/// </summary>
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class VoidMethodWithParamsMakeExpectations
				{
					/// <summary>
					/// Creates a new "simple" instance of a <see cref="global::MockTests.VoidMethodWithParams" />-based type.
					/// </summary>
					internal global::MockTests.VoidMethodWithParams Instance()
					{
						return new Mock();
					}
					
					private sealed class Mock
						: global::MockTests.VoidMethodWithParams
					{
						public Mock()
						{
						}
						
						public override bool Equals(object? @obj)
						{
							return default!;
						}
						
						public override int GetHashCode()
						{
							return default!;
						}
						
						public override string? ToString()
						{
							return default!;
						}
						
						public override void CallMe(params string[] @values)
						{
						}
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			"""";

		await TestAssistants.RunGeneratorAsync<RockGenerator>(code,
			[
				("MockTests.VoidMethodWithParams_Rock_Create.g.cs", createGeneratedCode),
				("MockTests.VoidMethodWithParams_Rock_Make.g.cs", makeGeneratedCode)
			],
			[]);
	}

	[Test]
	public static async Task GenerateForMethodWithParamsReturnsValueAsync()
	{
		var code =
			"""
			using Rocks;
			using System;

			[assembly: Rock(typeof(MockTests.ValueMethodWithParams), BuildType.Create | BuildType.Make)]

			namespace MockTests
			{
				public class ValueMethodWithParams
				{
					public virtual int CallMe(params string[] values) => default;
				}
			}
			""";

		var createGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			namespace MockTests;
			
			/// <summary>
			/// Contains mocking infrastructure code for <see cref="global::MockTests.ValueMethodWithParams"/>.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class ValueMethodWithParamsCreateExpectations
				: global::Rocks.Expectations
			{
				private readonly global::MockTests.ValueMethodWithParamsCreateExpectations.SetupsExpectations setups;
				
				/// <summary>
				/// Contains expectation setups for mockable members on <see cref="global::MockTests.ValueMethodWithParams"/>.
				/// </summary>
				internal sealed class SetupsExpectations
				{
					private readonly global::MockTests.ValueMethodWithParamsCreateExpectations parent;
				
					/// <summary>
					/// Creates a new <see cref="SetupsExpectations"/> instance.
					/// </summary>
					internal SetupsExpectations(global::MockTests.ValueMethodWithParamsCreateExpectations parent) =>
						this.parent = parent;
				
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.ValueMethodWithParams.Equals(Object)"/>.
					/// </summary>
					internal global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA Equals(global::Rocks.Argument<object?> @obj)
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@obj);
						
						var @handler = new global::MockTests.ValueMethodWithParamsCreateExpectations.Handler0
						{
							@obj = @obj,
						};
						
						this.parent.handlers0 ??= new(1);
						this.parent.handlers0.Add(@handler);
						return new(@handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.ValueMethodWithParams.GetHashCode()"/>.
					/// </summary>
					internal new global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE GetHashCode()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.ValueMethodWithParamsCreateExpectations.Handler1();
						this.parent.handlers1 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.ValueMethodWithParams.ToString()"/>.
					/// </summary>
					internal new global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.ToStringAdornments2D2816FE ToString()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.ValueMethodWithParamsCreateExpectations.Handler2();
						this.parent.handlers2 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.ValueMethodWithParams.CallMe()"/>.
					/// </summary>
					internal global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.CallMeAdornmentsED6F815B CallMe(global::Rocks.Argument<string[]> @values)
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@values);
						
						var @handler = new global::MockTests.ValueMethodWithParamsCreateExpectations.Handler3
						{
							@values = @values,
						};
						
						this.parent.handlers3 ??= new(1);
						this.parent.handlers3.Add(@handler);
						return new(@handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.ValueMethodWithParams.CallMe()"/>.
					/// </summary>
					internal global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.CallMeAdornmentsED6F815B CallMe(params string[] @values) =>
						this.CallMe(global::Rocks.Arg.Is(@values));
				}
				
				internal global::MockTests.ValueMethodWithParamsCreateExpectations.SetupsExpectations Setups => this.setups;
				
				internal sealed class Handler0
					: global::Rocks.Handler<global::System.Func<object?, bool>, bool>
				{
					internal global::Rocks.Argument<object?> @obj { get; set; }
				}
				private global::System.Collections.Generic.List<global::MockTests.ValueMethodWithParamsCreateExpectations.Handler0>? @handlers0;
				
				internal sealed class Handler1
					: global::Rocks.Handler<global::System.Func<int>, int>
				{ }
				private global::MockTests.ValueMethodWithParamsCreateExpectations.Handler1? @handlers1;
				
				internal sealed class Handler2
					: global::Rocks.Handler<global::System.Func<string?>, string?>
				{ }
				private global::MockTests.ValueMethodWithParamsCreateExpectations.Handler2? @handlers2;
				
				internal sealed class Handler3
					: global::Rocks.Handler<global::System.Func<string[], int>, int>
				{
					internal global::Rocks.Argument<string[]> @values { get; set; }
				}
				private global::System.Collections.Generic.List<global::MockTests.ValueMethodWithParamsCreateExpectations.Handler3>? @handlers3;
				
				/// <summary>
				/// Verifies expectations set for the <see cref="global::MockTests.ValueMethodWithParams"/>-based mock.
				/// </summary>
				public override void Verify()
				{
					if (!this.WasInstanceInvoked)
					{
						throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::MockTests.ValueMethodWithParamsCreateExpectations was never made."]);
					}
					else if (!this.WasExceptionThrown)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(global::Rocks.Expectations.Verify(this.handlers0, 0, typeof(Mock))); }
						if (this.handlers1 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers1], 1, typeof(Mock))); }
						if (this.handlers2 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers2], 2, typeof(Mock))); }
						if (this.handlers3 is not null) { failures.AddRange(global::Rocks.Expectations.Verify(this.handlers3, 3, typeof(Mock))); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::MockTests.ValueMethodWithParams
				{
					public Mock(global::MockTests.ValueMethodWithParamsCreateExpectations @expectations)
					{
						this.Expectations = @expectations;
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public override bool Equals(object? @obj)
					{
						if (this.Expectations.handlers0 is not null)
						{
							foreach (var @handler in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Expectations.handlers0))
							{
								if (@handler.@obj.IsValid(@obj!))
								{
									@handler.CallCount++;
									if (@handler.Exception is not null) { throw @handler.Exception; }
									var @result = @handler.Callback is not null ?
										@handler.Callback(@obj!) : @handler.ReturnValue;
									return @result!;
								}
							}
							
							this.Expectations.WasExceptionThrown = true;
							throw new global::Rocks.Exceptions.ExpectationException(
								$"""
								No handlers match for {typeof(Mock).GetMemberDescription(0)}
									obj: {@obj.FormatValue()}
								""");
						}
						else
						{
							return base.Equals(@obj: @obj!);
						}
					}
					
					[global::Rocks.MemberIdentifier(1)]
					public override int GetHashCode()
					{
						if (this.Expectations.handlers1 is not null)
						{
							var @handler = this.Expectations.handlers1;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.GetHashCode();
						}
					}
					
					[global::Rocks.MemberIdentifier(2)]
					public override string? ToString()
					{
						if (this.Expectations.handlers2 is not null)
						{
							var @handler = this.Expectations.handlers2;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.ToString();
						}
					}
					
					[global::Rocks.MemberIdentifier(3)]
					public override int CallMe(params string[] @values)
					{
						if (this.Expectations.handlers3 is not null)
						{
							foreach (var @handler in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Expectations.handlers3))
							{
								if (@handler.@values.IsValid(@values!))
								{
									@handler.CallCount++;
									if (@handler.Exception is not null) { throw @handler.Exception; }
									var @result = @handler.Callback is not null ?
										@handler.Callback(@values!) : @handler.ReturnValue;
									return @result!;
								}
							}
							
							this.Expectations.WasExceptionThrown = true;
							throw new global::Rocks.Exceptions.ExpectationException(
								$"""
								No handlers match for {typeof(Mock).GetMemberDescription(3)}
									values: {@values.FormatValue()}
								""");
						}
						else
						{
							return base.CallMe(@values: @values!);
						}
					}
					
					private global::MockTests.ValueMethodWithParamsCreateExpectations Expectations { get; }
				}
				
				public ValueMethodWithParamsCreateExpectations() => this.setups = new(this);
				
				/// <summary>
				/// Creates a new instance of a <see cref="global::MockTests.ValueMethodWithParams" />-based mock.
				/// </summary>
				/// <exception cref="global::Rocks.Exceptions.NewMockInstanceException">Thrown if a mock instance has already been created.</exception>
				internal global::MockTests.ValueMethodWithParams Instance()
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						return new Mock(this);
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					internal interface IAdornmentsForValueMethodWithParams<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForValueMethodWithParams<TAdornments>
					{ }
					
					internal sealed class EqualsAdornmentsE60CFEEA
						: global::Rocks.Adornments<EqualsAdornmentsE60CFEEA, global::MockTests.ValueMethodWithParamsCreateExpectations.Handler0, global::System.Func<object?, bool>, bool>, IAdornmentsForValueMethodWithParams<EqualsAdornmentsE60CFEEA>
					{
						internal EqualsAdornmentsE60CFEEA(global::MockTests.ValueMethodWithParamsCreateExpectations.Handler0 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class GetHashCodeAdornments2D2816FE
						: global::Rocks.Adornments<GetHashCodeAdornments2D2816FE, global::MockTests.ValueMethodWithParamsCreateExpectations.Handler1, global::System.Func<int>, int>, IAdornmentsForValueMethodWithParams<GetHashCodeAdornments2D2816FE>
					{
						internal GetHashCodeAdornments2D2816FE(global::MockTests.ValueMethodWithParamsCreateExpectations.Handler1 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class ToStringAdornments2D2816FE
						: global::Rocks.Adornments<ToStringAdornments2D2816FE, global::MockTests.ValueMethodWithParamsCreateExpectations.Handler2, global::System.Func<string?>, string?>, IAdornmentsForValueMethodWithParams<ToStringAdornments2D2816FE>
					{
						internal ToStringAdornments2D2816FE(global::MockTests.ValueMethodWithParamsCreateExpectations.Handler2 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class CallMeAdornmentsED6F815B
						: global::Rocks.Adornments<CallMeAdornmentsED6F815B, global::MockTests.ValueMethodWithParamsCreateExpectations.Handler3, global::System.Func<string[], int>, int>, IAdornmentsForValueMethodWithParams<CallMeAdornmentsED6F815B>
					{
						internal CallMeAdornmentsED6F815B(global::MockTests.ValueMethodWithParamsCreateExpectations.Handler3 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
				}
				
				internal void Remove(global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA adornments)
				{
					adornments.Remove(this.@handlers0);
					if (this.@handlers0?.Count == 0) { this.@handlers0 = null; }
				}
				
				internal void Remove(global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE adornments) =>
					this.@handlers1 = null;
				
				internal void Remove(global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.ToStringAdornments2D2816FE adornments) =>
					this.@handlers2 = null;
				
				internal void Remove(global::MockTests.ValueMethodWithParamsCreateExpectations.Adornments.CallMeAdornmentsED6F815B adornments)
				{
					adornments.Remove(this.@handlers3);
					if (this.@handlers3?.Count == 0) { this.@handlers3 = null; }
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			"""";

		var makeGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			namespace MockTests
			{
				/// <summary>
				/// Contains code to create a "simple" definition of <see cref="global::MockTests.ValueMethodWithParams"/>.
				/// </summary>
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class ValueMethodWithParamsMakeExpectations
				{
					/// <summary>
					/// Creates a new "simple" instance of a <see cref="global::MockTests.ValueMethodWithParams" />-based type.
					/// </summary>
					internal global::MockTests.ValueMethodWithParams Instance()
					{
						return new Mock();
					}
					
					private sealed class Mock
						: global::MockTests.ValueMethodWithParams
					{
						public Mock()
						{
						}
						
						public override bool Equals(object? @obj)
						{
							return default!;
						}
						
						public override int GetHashCode()
						{
							return default!;
						}
						
						public override string? ToString()
						{
							return default!;
						}
						
						public override int CallMe(params string[] @values)
						{
							return default!;
						}
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			"""";

 		await TestAssistants.RunGeneratorAsync<RockGenerator>(code,
			[
				("MockTests.ValueMethodWithParams_Rock_Create.g.cs", createGeneratedCode),
				("MockTests.ValueMethodWithParams_Rock_Make.g.cs", makeGeneratedCode)
			],
			[]);
	}

	[Test]
	public static async Task GenerateForInterfaceReturnsVoidAsync()
	{
		var code =
			"""
			using Rocks;
			using System;

			[assembly: Rock(typeof(MockTests.IHaveImplementation), BuildType.Create | BuildType.Make)]

			namespace MockTests
			{
				public interface IHaveImplementation
				{
					void Foo() { }
				}
			}
			""";

		var createGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			namespace MockTests;
			
			/// <summary>
			/// Contains mocking infrastructure code for <see cref="global::MockTests.IHaveImplementation"/>.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class IHaveImplementationCreateExpectations
				: global::Rocks.Expectations
			{
				private readonly global::MockTests.IHaveImplementationCreateExpectations.SetupsExpectations setups;
				
				/// <summary>
				/// Contains expectation setups for mockable members on <see cref="global::MockTests.IHaveImplementation"/>.
				/// </summary>
				internal sealed class SetupsExpectations
				{
					private readonly global::MockTests.IHaveImplementationCreateExpectations parent;
				
					/// <summary>
					/// Creates a new <see cref="SetupsExpectations"/> instance.
					/// </summary>
					internal SetupsExpectations(global::MockTests.IHaveImplementationCreateExpectations parent) =>
						this.parent = parent;
				
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.IHaveImplementation.Foo()"/>.
					/// </summary>
					internal global::MockTests.IHaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE Foo()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.IHaveImplementationCreateExpectations.Handler0();
						this.parent.handlers0 = handler;
						return new(handler, this.parent);
					}
				}
				
				internal global::MockTests.IHaveImplementationCreateExpectations.SetupsExpectations Setups => this.setups;
				
				internal sealed class Handler0
					: global::Rocks.Handler<global::System.Action>
				{ }
				private global::MockTests.IHaveImplementationCreateExpectations.Handler0? @handlers0;
				
				/// <summary>
				/// Verifies expectations set for the <see cref="global::MockTests.IHaveImplementation"/>-based mock.
				/// </summary>
				public override void Verify()
				{
					if (!this.WasInstanceInvoked)
					{
						throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::MockTests.IHaveImplementationCreateExpectations was never made."]);
					}
					else if (!this.WasExceptionThrown)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers0], 0, typeof(Mock))); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::MockTests.IHaveImplementation
				{
					private readonly global::MockTests.IHaveImplementation shimForShimIHaveImplementation;
					
					public Mock(global::MockTests.IHaveImplementationCreateExpectations @expectations)
					{
						(this.Expectations, this.shimForShimIHaveImplementation) = (@expectations, new ShimIHaveImplementation(this));
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public void Foo()
					{
						if (this.Expectations.handlers0 is not null)
						{
							var @handler = this.Expectations.handlers0;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							@handler.Callback?.Invoke();
						}
						else
						{
							this.shimForShimIHaveImplementation.Foo();
						}
					}
					
					private sealed class ShimIHaveImplementation
						: global::MockTests.IHaveImplementation
					{
						private readonly Mock mock;
						
						public ShimIHaveImplementation(Mock @mock) =>
							this.mock = @mock;
					}
					
					private global::MockTests.IHaveImplementationCreateExpectations Expectations { get; }
				}
				
				public IHaveImplementationCreateExpectations() => this.setups = new(this);
				
				/// <summary>
				/// Creates a new instance of a <see cref="global::MockTests.IHaveImplementation" />-based mock.
				/// </summary>
				/// <exception cref="global::Rocks.Exceptions.NewMockInstanceException">Thrown if a mock instance has already been created.</exception>
				internal global::MockTests.IHaveImplementation Instance()
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						return new Mock(this);
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					internal interface IAdornmentsForIHaveImplementation<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForIHaveImplementation<TAdornments>
					{ }
					
					internal sealed class FooAdornments2D2816FE
						: global::Rocks.Adornments<FooAdornments2D2816FE, global::MockTests.IHaveImplementationCreateExpectations.Handler0, global::System.Action>, IAdornmentsForIHaveImplementation<FooAdornments2D2816FE>
					{
						internal FooAdornments2D2816FE(global::MockTests.IHaveImplementationCreateExpectations.Handler0 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
				}
				
				internal void Remove(global::MockTests.IHaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE adornments) =>
					this.@handlers0 = null;
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			"""";

		var makeGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			namespace MockTests
			{
				/// <summary>
				/// Contains code to create a "simple" definition of <see cref="global::MockTests.IHaveImplementation"/>.
				/// </summary>
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class IHaveImplementationMakeExpectations
				{
					/// <summary>
					/// Creates a new "simple" instance of a <see cref="global::MockTests.IHaveImplementation" />-based type.
					/// </summary>
					internal global::MockTests.IHaveImplementation Instance()
					{
						return new Mock();
					}
					
					private sealed class Mock
						: global::MockTests.IHaveImplementation
					{
						public Mock()
						{
						}
						
						public void Foo()
						{
						}
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			"""";

		await TestAssistants.RunGeneratorAsync<RockGenerator>(code,
			[
				("MockTests.IHaveImplementation_Rock_Create.g.cs", createGeneratedCode),
				("MockTests.IHaveImplementation_Rock_Make.g.cs", makeGeneratedCode)
			],
			[]);
	}

	[Test]
	public static async Task GenerateForInterfaceReturnsValueAsync()
	{
		var code =
			"""
			using Rocks;
			using System;

			[assembly: Rock(typeof(MockTests.IHaveImplementation), BuildType.Create | BuildType.Make)]

			namespace MockTests
			{
				public interface IHaveImplementation
				{
					int Foo() => 3;
				}
			}
			""";

		var createGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			namespace MockTests;
			
			/// <summary>
			/// Contains mocking infrastructure code for <see cref="global::MockTests.IHaveImplementation"/>.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class IHaveImplementationCreateExpectations
				: global::Rocks.Expectations
			{
				private readonly global::MockTests.IHaveImplementationCreateExpectations.SetupsExpectations setups;
				
				/// <summary>
				/// Contains expectation setups for mockable members on <see cref="global::MockTests.IHaveImplementation"/>.
				/// </summary>
				internal sealed class SetupsExpectations
				{
					private readonly global::MockTests.IHaveImplementationCreateExpectations parent;
				
					/// <summary>
					/// Creates a new <see cref="SetupsExpectations"/> instance.
					/// </summary>
					internal SetupsExpectations(global::MockTests.IHaveImplementationCreateExpectations parent) =>
						this.parent = parent;
				
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.IHaveImplementation.Foo()"/>.
					/// </summary>
					internal global::MockTests.IHaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE Foo()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.IHaveImplementationCreateExpectations.Handler0();
						this.parent.handlers0 = handler;
						return new(handler, this.parent);
					}
				}
				
				internal global::MockTests.IHaveImplementationCreateExpectations.SetupsExpectations Setups => this.setups;
				
				internal sealed class Handler0
					: global::Rocks.Handler<global::System.Func<int>, int>
				{ }
				private global::MockTests.IHaveImplementationCreateExpectations.Handler0? @handlers0;
				
				/// <summary>
				/// Verifies expectations set for the <see cref="global::MockTests.IHaveImplementation"/>-based mock.
				/// </summary>
				public override void Verify()
				{
					if (!this.WasInstanceInvoked)
					{
						throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::MockTests.IHaveImplementationCreateExpectations was never made."]);
					}
					else if (!this.WasExceptionThrown)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers0], 0, typeof(Mock))); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::MockTests.IHaveImplementation
				{
					private readonly global::MockTests.IHaveImplementation shimForShimIHaveImplementation;
					
					public Mock(global::MockTests.IHaveImplementationCreateExpectations @expectations)
					{
						(this.Expectations, this.shimForShimIHaveImplementation) = (@expectations, new ShimIHaveImplementation(this));
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public int Foo()
					{
						if (this.Expectations.handlers0 is not null)
						{
							var @handler = this.Expectations.handlers0;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return this.shimForShimIHaveImplementation.Foo();
						}
					}
					
					private sealed class ShimIHaveImplementation
						: global::MockTests.IHaveImplementation
					{
						private readonly Mock mock;
						
						public ShimIHaveImplementation(Mock @mock) =>
							this.mock = @mock;
					}
					
					private global::MockTests.IHaveImplementationCreateExpectations Expectations { get; }
				}
				
				public IHaveImplementationCreateExpectations() => this.setups = new(this);
				
				/// <summary>
				/// Creates a new instance of a <see cref="global::MockTests.IHaveImplementation" />-based mock.
				/// </summary>
				/// <exception cref="global::Rocks.Exceptions.NewMockInstanceException">Thrown if a mock instance has already been created.</exception>
				internal global::MockTests.IHaveImplementation Instance()
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						return new Mock(this);
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					internal interface IAdornmentsForIHaveImplementation<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForIHaveImplementation<TAdornments>
					{ }
					
					internal sealed class FooAdornments2D2816FE
						: global::Rocks.Adornments<FooAdornments2D2816FE, global::MockTests.IHaveImplementationCreateExpectations.Handler0, global::System.Func<int>, int>, IAdornmentsForIHaveImplementation<FooAdornments2D2816FE>
					{
						internal FooAdornments2D2816FE(global::MockTests.IHaveImplementationCreateExpectations.Handler0 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
				}
				
				internal void Remove(global::MockTests.IHaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE adornments) =>
					this.@handlers0 = null;
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			"""";

		var makeGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			namespace MockTests
			{
				/// <summary>
				/// Contains code to create a "simple" definition of <see cref="global::MockTests.IHaveImplementation"/>.
				/// </summary>
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class IHaveImplementationMakeExpectations
				{
					/// <summary>
					/// Creates a new "simple" instance of a <see cref="global::MockTests.IHaveImplementation" />-based type.
					/// </summary>
					internal global::MockTests.IHaveImplementation Instance()
					{
						return new Mock();
					}
					
					private sealed class Mock
						: global::MockTests.IHaveImplementation
					{
						public Mock()
						{
						}
						
						public int Foo()
						{
							return default!;
						}
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			"""";

		await TestAssistants.RunGeneratorAsync<RockGenerator>(code,
			[
				("MockTests.IHaveImplementation_Rock_Create.g.cs", createGeneratedCode),
				("MockTests.IHaveImplementation_Rock_Make.g.cs", makeGeneratedCode)
			],
			[]);
	}

	[Test]
	public static async Task GenerateForClassReturnsVoidAsync()
	{
		var code =
			"""
			using Rocks;
			using System;

			[assembly: Rock(typeof(MockTests.HaveImplementation), BuildType.Create | BuildType.Make)]

			namespace MockTests
			{
				public class HaveImplementation
				{
					public virtual void Foo() { }
				}
			}
			""";

		var createGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			namespace MockTests;
			
			/// <summary>
			/// Contains mocking infrastructure code for <see cref="global::MockTests.HaveImplementation"/>.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class HaveImplementationCreateExpectations
				: global::Rocks.Expectations
			{
				private readonly global::MockTests.HaveImplementationCreateExpectations.SetupsExpectations setups;
				
				/// <summary>
				/// Contains expectation setups for mockable members on <see cref="global::MockTests.HaveImplementation"/>.
				/// </summary>
				internal sealed class SetupsExpectations
				{
					private readonly global::MockTests.HaveImplementationCreateExpectations parent;
				
					/// <summary>
					/// Creates a new <see cref="SetupsExpectations"/> instance.
					/// </summary>
					internal SetupsExpectations(global::MockTests.HaveImplementationCreateExpectations parent) =>
						this.parent = parent;
				
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.Equals(Object)"/>.
					/// </summary>
					internal global::MockTests.HaveImplementationCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA Equals(global::Rocks.Argument<object?> @obj)
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@obj);
						
						var @handler = new global::MockTests.HaveImplementationCreateExpectations.Handler0
						{
							@obj = @obj,
						};
						
						this.parent.handlers0 ??= new(1);
						this.parent.handlers0.Add(@handler);
						return new(@handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.GetHashCode()"/>.
					/// </summary>
					internal new global::MockTests.HaveImplementationCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE GetHashCode()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.HaveImplementationCreateExpectations.Handler1();
						this.parent.handlers1 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.ToString()"/>.
					/// </summary>
					internal new global::MockTests.HaveImplementationCreateExpectations.Adornments.ToStringAdornments2D2816FE ToString()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.HaveImplementationCreateExpectations.Handler2();
						this.parent.handlers2 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.Foo()"/>.
					/// </summary>
					internal global::MockTests.HaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE Foo()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.HaveImplementationCreateExpectations.Handler3();
						this.parent.handlers3 = handler;
						return new(handler, this.parent);
					}
				}
				
				internal global::MockTests.HaveImplementationCreateExpectations.SetupsExpectations Setups => this.setups;
				
				internal sealed class Handler0
					: global::Rocks.Handler<global::System.Func<object?, bool>, bool>
				{
					internal global::Rocks.Argument<object?> @obj { get; set; }
				}
				private global::System.Collections.Generic.List<global::MockTests.HaveImplementationCreateExpectations.Handler0>? @handlers0;
				
				internal sealed class Handler1
					: global::Rocks.Handler<global::System.Func<int>, int>
				{ }
				private global::MockTests.HaveImplementationCreateExpectations.Handler1? @handlers1;
				
				internal sealed class Handler2
					: global::Rocks.Handler<global::System.Func<string?>, string?>
				{ }
				private global::MockTests.HaveImplementationCreateExpectations.Handler2? @handlers2;
				
				internal sealed class Handler3
					: global::Rocks.Handler<global::System.Action>
				{ }
				private global::MockTests.HaveImplementationCreateExpectations.Handler3? @handlers3;
				
				/// <summary>
				/// Verifies expectations set for the <see cref="global::MockTests.HaveImplementation"/>-based mock.
				/// </summary>
				public override void Verify()
				{
					if (!this.WasInstanceInvoked)
					{
						throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::MockTests.HaveImplementationCreateExpectations was never made."]);
					}
					else if (!this.WasExceptionThrown)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(global::Rocks.Expectations.Verify(this.handlers0, 0, typeof(Mock))); }
						if (this.handlers1 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers1], 1, typeof(Mock))); }
						if (this.handlers2 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers2], 2, typeof(Mock))); }
						if (this.handlers3 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers3], 3, typeof(Mock))); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::MockTests.HaveImplementation
				{
					public Mock(global::MockTests.HaveImplementationCreateExpectations @expectations)
					{
						this.Expectations = @expectations;
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public override bool Equals(object? @obj)
					{
						if (this.Expectations.handlers0 is not null)
						{
							foreach (var @handler in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Expectations.handlers0))
							{
								if (@handler.@obj.IsValid(@obj!))
								{
									@handler.CallCount++;
									if (@handler.Exception is not null) { throw @handler.Exception; }
									var @result = @handler.Callback is not null ?
										@handler.Callback(@obj!) : @handler.ReturnValue;
									return @result!;
								}
							}
							
							this.Expectations.WasExceptionThrown = true;
							throw new global::Rocks.Exceptions.ExpectationException(
								$"""
								No handlers match for {typeof(Mock).GetMemberDescription(0)}
									obj: {@obj.FormatValue()}
								""");
						}
						else
						{
							return base.Equals(@obj: @obj!);
						}
					}
					
					[global::Rocks.MemberIdentifier(1)]
					public override int GetHashCode()
					{
						if (this.Expectations.handlers1 is not null)
						{
							var @handler = this.Expectations.handlers1;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.GetHashCode();
						}
					}
					
					[global::Rocks.MemberIdentifier(2)]
					public override string? ToString()
					{
						if (this.Expectations.handlers2 is not null)
						{
							var @handler = this.Expectations.handlers2;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.ToString();
						}
					}
					
					[global::Rocks.MemberIdentifier(3)]
					public override void Foo()
					{
						if (this.Expectations.handlers3 is not null)
						{
							var @handler = this.Expectations.handlers3;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							@handler.Callback?.Invoke();
						}
						else
						{
							base.Foo();
						}
					}
					
					private global::MockTests.HaveImplementationCreateExpectations Expectations { get; }
				}
				
				public HaveImplementationCreateExpectations() => this.setups = new(this);
				
				/// <summary>
				/// Creates a new instance of a <see cref="global::MockTests.HaveImplementation" />-based mock.
				/// </summary>
				/// <exception cref="global::Rocks.Exceptions.NewMockInstanceException">Thrown if a mock instance has already been created.</exception>
				internal global::MockTests.HaveImplementation Instance()
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						return new Mock(this);
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					internal interface IAdornmentsForHaveImplementation<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForHaveImplementation<TAdornments>
					{ }
					
					internal sealed class EqualsAdornmentsE60CFEEA
						: global::Rocks.Adornments<EqualsAdornmentsE60CFEEA, global::MockTests.HaveImplementationCreateExpectations.Handler0, global::System.Func<object?, bool>, bool>, IAdornmentsForHaveImplementation<EqualsAdornmentsE60CFEEA>
					{
						internal EqualsAdornmentsE60CFEEA(global::MockTests.HaveImplementationCreateExpectations.Handler0 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class GetHashCodeAdornments2D2816FE
						: global::Rocks.Adornments<GetHashCodeAdornments2D2816FE, global::MockTests.HaveImplementationCreateExpectations.Handler1, global::System.Func<int>, int>, IAdornmentsForHaveImplementation<GetHashCodeAdornments2D2816FE>
					{
						internal GetHashCodeAdornments2D2816FE(global::MockTests.HaveImplementationCreateExpectations.Handler1 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class ToStringAdornments2D2816FE
						: global::Rocks.Adornments<ToStringAdornments2D2816FE, global::MockTests.HaveImplementationCreateExpectations.Handler2, global::System.Func<string?>, string?>, IAdornmentsForHaveImplementation<ToStringAdornments2D2816FE>
					{
						internal ToStringAdornments2D2816FE(global::MockTests.HaveImplementationCreateExpectations.Handler2 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class FooAdornments2D2816FE
						: global::Rocks.Adornments<FooAdornments2D2816FE, global::MockTests.HaveImplementationCreateExpectations.Handler3, global::System.Action>, IAdornmentsForHaveImplementation<FooAdornments2D2816FE>
					{
						internal FooAdornments2D2816FE(global::MockTests.HaveImplementationCreateExpectations.Handler3 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
				}
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA adornments)
				{
					adornments.Remove(this.@handlers0);
					if (this.@handlers0?.Count == 0) { this.@handlers0 = null; }
				}
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE adornments) =>
					this.@handlers1 = null;
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.ToStringAdornments2D2816FE adornments) =>
					this.@handlers2 = null;
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE adornments) =>
					this.@handlers3 = null;
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			"""";

		var makeGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			namespace MockTests
			{
				/// <summary>
				/// Contains code to create a "simple" definition of <see cref="global::MockTests.HaveImplementation"/>.
				/// </summary>
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class HaveImplementationMakeExpectations
				{
					/// <summary>
					/// Creates a new "simple" instance of a <see cref="global::MockTests.HaveImplementation" />-based type.
					/// </summary>
					internal global::MockTests.HaveImplementation Instance()
					{
						return new Mock();
					}
					
					private sealed class Mock
						: global::MockTests.HaveImplementation
					{
						public Mock()
						{
						}
						
						public override bool Equals(object? @obj)
						{
							return default!;
						}
						
						public override int GetHashCode()
						{
							return default!;
						}
						
						public override string? ToString()
						{
							return default!;
						}
						
						public override void Foo()
						{
						}
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			"""";

		await TestAssistants.RunGeneratorAsync<RockGenerator>(code,
			[
				("MockTests.HaveImplementation_Rock_Create.g.cs", createGeneratedCode),
				("MockTests.HaveImplementation_Rock_Make.g.cs", makeGeneratedCode)
			],
			[]);
	}

	[Test]
	public static async Task GenerateForClassReturnsValueAsync()
	{
		var code =
			"""
			using Rocks;
			using System;

			[assembly: Rock(typeof(MockTests.HaveImplementation), BuildType.Create | BuildType.Make)]

			namespace MockTests
			{
				public class HaveImplementation
				{
					public virtual int Foo() => 3;
				}
			}
			""";

		var createGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			using Rocks.Extensions;
			
			namespace MockTests;
			
			/// <summary>
			/// Contains mocking infrastructure code for <see cref="global::MockTests.HaveImplementation"/>.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class HaveImplementationCreateExpectations
				: global::Rocks.Expectations
			{
				private readonly global::MockTests.HaveImplementationCreateExpectations.SetupsExpectations setups;
				
				/// <summary>
				/// Contains expectation setups for mockable members on <see cref="global::MockTests.HaveImplementation"/>.
				/// </summary>
				internal sealed class SetupsExpectations
				{
					private readonly global::MockTests.HaveImplementationCreateExpectations parent;
				
					/// <summary>
					/// Creates a new <see cref="SetupsExpectations"/> instance.
					/// </summary>
					internal SetupsExpectations(global::MockTests.HaveImplementationCreateExpectations parent) =>
						this.parent = parent;
				
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.Equals(Object)"/>.
					/// </summary>
					internal global::MockTests.HaveImplementationCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA Equals(global::Rocks.Argument<object?> @obj)
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						global::System.ArgumentNullException.ThrowIfNull(@obj);
						
						var @handler = new global::MockTests.HaveImplementationCreateExpectations.Handler0
						{
							@obj = @obj,
						};
						
						this.parent.handlers0 ??= new(1);
						this.parent.handlers0.Add(@handler);
						return new(@handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.GetHashCode()"/>.
					/// </summary>
					internal new global::MockTests.HaveImplementationCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE GetHashCode()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.HaveImplementationCreateExpectations.Handler1();
						this.parent.handlers1 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.ToString()"/>.
					/// </summary>
					internal new global::MockTests.HaveImplementationCreateExpectations.Adornments.ToStringAdornments2D2816FE ToString()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.HaveImplementationCreateExpectations.Handler2();
						this.parent.handlers2 = handler;
						return new(handler, this.parent);
					}
					
					/// <summary>
					/// Sets an expectation for <see cref="global::MockTests.HaveImplementation.Foo()"/>.
					/// </summary>
					internal global::MockTests.HaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE Foo()
					{
						global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
						var handler = new global::MockTests.HaveImplementationCreateExpectations.Handler3();
						this.parent.handlers3 = handler;
						return new(handler, this.parent);
					}
				}
				
				internal global::MockTests.HaveImplementationCreateExpectations.SetupsExpectations Setups => this.setups;
				
				internal sealed class Handler0
					: global::Rocks.Handler<global::System.Func<object?, bool>, bool>
				{
					internal global::Rocks.Argument<object?> @obj { get; set; }
				}
				private global::System.Collections.Generic.List<global::MockTests.HaveImplementationCreateExpectations.Handler0>? @handlers0;
				
				internal sealed class Handler1
					: global::Rocks.Handler<global::System.Func<int>, int>
				{ }
				private global::MockTests.HaveImplementationCreateExpectations.Handler1? @handlers1;
				
				internal sealed class Handler2
					: global::Rocks.Handler<global::System.Func<string?>, string?>
				{ }
				private global::MockTests.HaveImplementationCreateExpectations.Handler2? @handlers2;
				
				internal sealed class Handler3
					: global::Rocks.Handler<global::System.Func<int>, int>
				{ }
				private global::MockTests.HaveImplementationCreateExpectations.Handler3? @handlers3;
				
				/// <summary>
				/// Verifies expectations set for the <see cref="global::MockTests.HaveImplementation"/>-based mock.
				/// </summary>
				public override void Verify()
				{
					if (!this.WasInstanceInvoked)
					{
						throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::MockTests.HaveImplementationCreateExpectations was never made."]);
					}
					else if (!this.WasExceptionThrown)
					{
						var failures = new global::System.Collections.Generic.List<string>();
				
						if (this.handlers0 is not null) { failures.AddRange(global::Rocks.Expectations.Verify(this.handlers0, 0, typeof(Mock))); }
						if (this.handlers1 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers1], 1, typeof(Mock))); }
						if (this.handlers2 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers2], 2, typeof(Mock))); }
						if (this.handlers3 is not null) { failures.AddRange(global::Rocks.Expectations.Verify([this.handlers3], 3, typeof(Mock))); }
				
						if (failures.Count > 0)
						{
							throw new global::Rocks.Exceptions.VerificationException(failures);
						}
					}
				}
				
				private sealed class Mock
					: global::MockTests.HaveImplementation
				{
					public Mock(global::MockTests.HaveImplementationCreateExpectations @expectations)
					{
						this.Expectations = @expectations;
					}
					
					[global::Rocks.MemberIdentifier(0)]
					public override bool Equals(object? @obj)
					{
						if (this.Expectations.handlers0 is not null)
						{
							foreach (var @handler in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(this.Expectations.handlers0))
							{
								if (@handler.@obj.IsValid(@obj!))
								{
									@handler.CallCount++;
									if (@handler.Exception is not null) { throw @handler.Exception; }
									var @result = @handler.Callback is not null ?
										@handler.Callback(@obj!) : @handler.ReturnValue;
									return @result!;
								}
							}
							
							this.Expectations.WasExceptionThrown = true;
							throw new global::Rocks.Exceptions.ExpectationException(
								$"""
								No handlers match for {typeof(Mock).GetMemberDescription(0)}
									obj: {@obj.FormatValue()}
								""");
						}
						else
						{
							return base.Equals(@obj: @obj!);
						}
					}
					
					[global::Rocks.MemberIdentifier(1)]
					public override int GetHashCode()
					{
						if (this.Expectations.handlers1 is not null)
						{
							var @handler = this.Expectations.handlers1;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.GetHashCode();
						}
					}
					
					[global::Rocks.MemberIdentifier(2)]
					public override string? ToString()
					{
						if (this.Expectations.handlers2 is not null)
						{
							var @handler = this.Expectations.handlers2;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.ToString();
						}
					}
					
					[global::Rocks.MemberIdentifier(3)]
					public override int Foo()
					{
						if (this.Expectations.handlers3 is not null)
						{
							var @handler = this.Expectations.handlers3;
							@handler.CallCount++;
							if (@handler.Exception is not null) { throw @handler.Exception; }
							var @result = @handler.Callback is not null ?
								@handler.Callback() : @handler.ReturnValue;
							return @result!;
						}
						else
						{
							return base.Foo();
						}
					}
					
					private global::MockTests.HaveImplementationCreateExpectations Expectations { get; }
				}
				
				public HaveImplementationCreateExpectations() => this.setups = new(this);
				
				/// <summary>
				/// Creates a new instance of a <see cref="global::MockTests.HaveImplementation" />-based mock.
				/// </summary>
				/// <exception cref="global::Rocks.Exceptions.NewMockInstanceException">Thrown if a mock instance has already been created.</exception>
				internal global::MockTests.HaveImplementation Instance()
				{
					if (!this.WasInstanceInvoked)
					{
						this.WasInstanceInvoked = true;
						return new Mock(this);
					}
					else
					{
						throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
					}
				}
				
				internal static class Adornments
				{
					internal interface IAdornmentsForHaveImplementation<TAdornments>
						: global::Rocks.IAdornments<TAdornments>
						where TAdornments : IAdornmentsForHaveImplementation<TAdornments>
					{ }
					
					internal sealed class EqualsAdornmentsE60CFEEA
						: global::Rocks.Adornments<EqualsAdornmentsE60CFEEA, global::MockTests.HaveImplementationCreateExpectations.Handler0, global::System.Func<object?, bool>, bool>, IAdornmentsForHaveImplementation<EqualsAdornmentsE60CFEEA>
					{
						internal EqualsAdornmentsE60CFEEA(global::MockTests.HaveImplementationCreateExpectations.Handler0 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class GetHashCodeAdornments2D2816FE
						: global::Rocks.Adornments<GetHashCodeAdornments2D2816FE, global::MockTests.HaveImplementationCreateExpectations.Handler1, global::System.Func<int>, int>, IAdornmentsForHaveImplementation<GetHashCodeAdornments2D2816FE>
					{
						internal GetHashCodeAdornments2D2816FE(global::MockTests.HaveImplementationCreateExpectations.Handler1 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class ToStringAdornments2D2816FE
						: global::Rocks.Adornments<ToStringAdornments2D2816FE, global::MockTests.HaveImplementationCreateExpectations.Handler2, global::System.Func<string?>, string?>, IAdornmentsForHaveImplementation<ToStringAdornments2D2816FE>
					{
						internal ToStringAdornments2D2816FE(global::MockTests.HaveImplementationCreateExpectations.Handler2 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
					
					internal sealed class FooAdornments2D2816FE
						: global::Rocks.Adornments<FooAdornments2D2816FE, global::MockTests.HaveImplementationCreateExpectations.Handler3, global::System.Func<int>, int>, IAdornmentsForHaveImplementation<FooAdornments2D2816FE>
					{
						internal FooAdornments2D2816FE(global::MockTests.HaveImplementationCreateExpectations.Handler3 handler, global::Rocks.Expectations expectations)
							: base(handler, expectations) { }
					}
				}
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.EqualsAdornmentsE60CFEEA adornments)
				{
					adornments.Remove(this.@handlers0);
					if (this.@handlers0?.Count == 0) { this.@handlers0 = null; }
				}
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.GetHashCodeAdornments2D2816FE adornments) =>
					this.@handlers1 = null;
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.ToStringAdornments2D2816FE adornments) =>
					this.@handlers2 = null;
				
				internal void Remove(global::MockTests.HaveImplementationCreateExpectations.Adornments.FooAdornments2D2816FE adornments) =>
					this.@handlers3 = null;
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			"""";

		var makeGeneratedCode =
			""""
			// <auto-generated/>
			
			#pragma warning disable CS8618
			#pragma warning disable CS8633
			#pragma warning disable CS8714
			#pragma warning disable CS8775
			
			#nullable enable
			
			namespace MockTests
			{
				/// <summary>
				/// Contains code to create a "simple" definition of <see cref="global::MockTests.HaveImplementation"/>.
				/// </summary>
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class HaveImplementationMakeExpectations
				{
					/// <summary>
					/// Creates a new "simple" instance of a <see cref="global::MockTests.HaveImplementation" />-based type.
					/// </summary>
					internal global::MockTests.HaveImplementation Instance()
					{
						return new Mock();
					}
					
					private sealed class Mock
						: global::MockTests.HaveImplementation
					{
						public Mock()
						{
						}
						
						public override bool Equals(object? @obj)
						{
							return default!;
						}
						
						public override int GetHashCode()
						{
							return default!;
						}
						
						public override string? ToString()
						{
							return default!;
						}
						
						public override int Foo()
						{
							return default!;
						}
					}
				}
			}
			
			#pragma warning restore CS8618
			#pragma warning restore CS8633
			#pragma warning restore CS8714
			#pragma warning restore CS8775
			
			"""";

		await TestAssistants.RunGeneratorAsync<RockGenerator>(code,
			[
				("MockTests.HaveImplementation_Rock_Create.g.cs", createGeneratedCode),
				("MockTests.HaveImplementation_Rock_Make.g.cs", makeGeneratedCode)
			],
			[]);
	}
}