// <auto-generated/>

#pragma warning disable CS8618
#pragma warning disable CS8633
#pragma warning disable CS8714
#pragma warning disable CS8775

#nullable enable

using Rocks.Extensions;

namespace Rocks.Experimental
{
	public interface IInterfaceMethodReturn
	{
		int NoParameters();
		int OneParameter(int a);
		int MultipleParameters(int a, string b);
		int GetAndSetData { get; set; }
		int this[int a, string b] { get; set; }
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal sealed class IInterfaceCreateExpectations
		: global::Rocks.Expectations
	{
		internal global::Rocks.Experimental.IInterfaceCreateExpectations.Adornments.AdornmentsForHandler0 NoParameters()
		{
			global::Rocks.Exceptions.ExpectationException.ThrowIf(this.WasInstanceInvoked);
			var handler = new global::Rocks.Experimental.IInterfaceCreateExpectations.Handler0();
			if (this.handlers0 is null) { this.handlers0 = new(handler); }
			else { this.handlers0.Add(handler); }
			return new(handler);
		}

		internal global::Rocks.Experimental.IInterfaceCreateExpectations.Adornments.AdornmentsForHandler1 OneParameter(global::Rocks.Argument<int> @a)
		{
			global::Rocks.Exceptions.ExpectationException.ThrowIf(this.WasInstanceInvoked);
			global::System.ArgumentNullException.ThrowIfNull(@a);

			var @handler = new global::Rocks.Experimental.IInterfaceCreateExpectations.Handler1
			{
				@a = @a,
			};

			if (this.handlers1 is null) { this.handlers1 = new(@handler); }
			else { this.handlers1.Add(@handler); }
			return new(@handler);
		}

		internal global::Rocks.Experimental.IInterfaceCreateExpectations.Adornments.AdornmentsForHandler2 MultipleParameters(global::Rocks.Argument<int> @a, global::Rocks.Argument<string> @b)
		{
			global::Rocks.Exceptions.ExpectationException.ThrowIf(this.WasInstanceInvoked);
			global::System.ArgumentNullException.ThrowIfNull(@a);
			global::System.ArgumentNullException.ThrowIfNull(@b);

			var @handler = new global::Rocks.Experimental.IInterfaceCreateExpectations.Handler2
			{
				@a = @a,
				@b = @b,
			};

			if (this.handlers2 is null) { this.handlers2 = new(@handler); }
			else { this.handlers2.Add(@handler); }
			return new(@handler);
		}

		internal sealed class GetAndSetDataPropertyExpectations
		{
			private readonly global::Rocks.Experimental.IInterfaceCreateExpectations parent;

			internal GetAndSetDataPropertyExpectations(global::Rocks.Experimental.IInterfaceCreateExpectations parent) => this.parent = parent;

			internal global::Rocks.Experimental.IInterfaceCreateExpectations.Adornments.AdornmentsForHandler3 Gets()
			{
				global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
				var handler = new global::Rocks.Experimental.IInterfaceCreateExpectations.Handler3();
				if (this.parent.handlers3 is null) { this.parent.handlers3 = new(handler); }
				else { this.parent.handlers3.Add(handler); }
				return new(handler);
			}

			internal global::Rocks.Experimental.IInterfaceCreateExpectations.Adornments.AdornmentsForHandler4 Sets(global::Rocks.Argument<int> @value)
			{
				global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
				global::System.ArgumentNullException.ThrowIfNull(@value);

				var handler = new global::Rocks.Experimental.IInterfaceCreateExpectations.Handler4
				{
					value = @value,
				};

				if (this.parent.handlers4 is null) { this.parent.handlers4 = new(handler); }
				else { this.parent.handlers4.Add(handler); }
				return new(handler);
			}
		}

		internal global::Rocks.Experimental.IInterfaceCreateExpectations.GetAndSetDataPropertyExpectations GetAndSetData { get => new(this); }

		internal sealed class Indexer0Expectations
		{
			private readonly global::Rocks.Experimental.IInterfaceCreateExpectations parent;
			private readonly global::Rocks.Argument<int> a;
			private readonly global::Rocks.Argument<string> @b;

			internal Indexer0Expectations(global::Rocks.Experimental.IInterfaceCreateExpectations parent, global::Rocks.Argument<int> @a, global::Rocks.Argument<string> @b)
			{
				global::System.ArgumentNullException.ThrowIfNull(@a);
				global::System.ArgumentNullException.ThrowIfNull(@b);
				this.parent = parent;
				this.a = @a;
				this.@b = @b;
			}

			internal global::Rocks.Experimental.IInterfaceCreateExpectations.Adornments.AdornmentsForHandler5 Gets()
			{
				global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
				var handler = new global::Rocks.Experimental.IInterfaceCreateExpectations.Handler5()
				{
					a = this.a,
					b = this.b
				};
				if (this.parent.handlers5 is null) { this.parent.handlers5 = new(handler); }
				else { this.parent.handlers5.Add(handler); }
				return new(handler);
			}

			internal global::Rocks.Experimental.IInterfaceCreateExpectations.Adornments.AdornmentsForHandler6 Sets(global::Rocks.Argument<int> @value)
			{
				global::Rocks.Exceptions.ExpectationException.ThrowIf(this.parent.WasInstanceInvoked);
				global::System.ArgumentNullException.ThrowIfNull(@value);

				var handler = new global::Rocks.Experimental.IInterfaceCreateExpectations.Handler6
				{
					a = this.a,
					b = this.b,
					value = @value,
				};

				if (this.parent.handlers6 is null) { this.parent.handlers6 = new(handler); }
				else { this.parent.handlers6.Add(handler); }
				return new(handler);
			}
		}

		internal global::Rocks.Experimental.IInterfaceCreateExpectations.Indexer0Expectations this[global::Rocks.Argument<int> @a, global::Rocks.Argument<string> @b] { get => new(this, @a, @b); }

		internal sealed class Handler0
			: global::Rocks.Handler<global::System.Func<int>, int>
		{ }
		private global::Rocks.Handlers<global::Rocks.Experimental.IInterfaceCreateExpectations.Handler0>? @handlers0;

		internal sealed class Handler1
			: global::Rocks.Handler<global::System.Func<int, int>, int>
		{
			public global::Rocks.Argument<int> @a { get; set; }
		}
		private global::Rocks.Handlers<global::Rocks.Experimental.IInterfaceCreateExpectations.Handler1>? @handlers1;

		internal sealed class Handler2
			: global::Rocks.Handler<global::System.Func<int, string, int>, int>
		{
			public global::Rocks.Argument<int> @a { get; set; }
			public global::Rocks.Argument<string> @b { get; set; }
		}
		private global::Rocks.Handlers<global::Rocks.Experimental.IInterfaceCreateExpectations.Handler2>? @handlers2;

		internal sealed class Handler3
			: global::Rocks.Handler<global::System.Func<int>, int>
		{ }
		private global::Rocks.Handlers<global::Rocks.Experimental.IInterfaceCreateExpectations.Handler3>? @handlers3;

		internal sealed class Handler4
			: global::Rocks.Handler<global::System.Action<int>>
		{
			public global::Rocks.Argument<int> @value { get; set; }
		}
		private global::Rocks.Handlers<global::Rocks.Experimental.IInterfaceCreateExpectations.Handler4>? @handlers4;

		internal sealed class Handler5
			: global::Rocks.Handler<global::System.Func<int, string, int>, int>
		{
			public global::Rocks.Argument<int> @a { get; set; }
			public global::Rocks.Argument<string> @b { get; set; }
		}
		private global::Rocks.Handlers<global::Rocks.Experimental.IInterfaceCreateExpectations.Handler5>? @handlers5;

		internal sealed class Handler6
			: global::Rocks.Handler<global::System.Action<int, string, int>>
		{
			public global::Rocks.Argument<int> @a { get; set; }
			public global::Rocks.Argument<string> @b { get; set; }
			public global::Rocks.Argument<int> @value { get; set; }
		}
		private global::Rocks.Handlers<global::Rocks.Experimental.IInterfaceCreateExpectations.Handler6>? @handlers6;

		public override void Verify()
		{
			if (!this.WasInstanceInvoked)
			{
				throw new global::Rocks.Exceptions.VerificationException([$"An instance of global::Rocks.Experimental.IInterfaceMethodReturnCreateExpectations was never made."]);
			}
			else if (!this.WasExceptionThrown)
			{
				var failures = new global::System.Collections.Generic.List<string>();

				if (this.handlers0 is not null) { failures.AddRange(this.Verify(this.handlers0, 0)); }
				if (this.handlers1 is not null) { failures.AddRange(this.Verify(this.handlers1, 1)); }
				if (this.handlers2 is not null) { failures.AddRange(this.Verify(this.handlers2, 2)); }
				if (this.handlers3 is not null) { failures.AddRange(this.Verify(this.handlers3, 3)); }
				if (this.handlers4 is not null) { failures.AddRange(this.Verify(this.handlers4, 4)); }
				if (this.handlers5 is not null) { failures.AddRange(this.Verify(this.handlers5, 5)); }
				if (this.handlers6 is not null) { failures.AddRange(this.Verify(this.handlers6, 6)); }

				if (failures.Count > 0)
				{
					throw new global::Rocks.Exceptions.VerificationException(failures);
				}
			}
		}

		private sealed class Mock
			: global::Rocks.Experimental.IInterfaceMethodReturn
		{
			public Mock(global::Rocks.Experimental.IInterfaceCreateExpectations @expectations)
			{
				this.Expectations = @expectations;
			}

			[global::Rocks.MemberIdentifier(0)]
			public int NoParameters()
			{
				if (this.Expectations.handlers0 is not null)
				{
					var @handler = this.Expectations.handlers0.First;
					@handler.CallCount++;
					var @result = @handler.Callback is not null ?
						@handler.Callback() : @handler.ReturnValue;
					return @result!;
				}

				this.Expectations.WasExceptionThrown = true;
				throw new global::Rocks.Exceptions.ExpectationException(
					$"""
					No handlers were found for {this.GetType().GetMemberDescription(0)}
					""");
			}

			[global::Rocks.MemberIdentifier(1)]
			public int OneParameter(int @a)
			{
				if (this.Expectations.handlers1 is not null)
				{
					foreach (var @handler in this.Expectations.handlers1)
					{
						if (@handler.@a.IsValid(@a!))
						{
							@handler.CallCount++;
							var @result = @handler.Callback is not null ?
								@handler.Callback(@a!) : @handler.ReturnValue;
							return @result!;
						}
					}

					this.Expectations.WasExceptionThrown = true;
					throw new global::Rocks.Exceptions.ExpectationException(
						$"""
						No handlers match for {this.GetType().GetMemberDescription(1)}
							a: {@a.FormatValue()}
						""");
				}

				this.Expectations.WasExceptionThrown = true;
				throw new global::Rocks.Exceptions.ExpectationException(
					$"""
					No handlers were found for {this.GetType().GetMemberDescription(1)}
						a: {@a.FormatValue()}
					""");
			}

			[global::Rocks.MemberIdentifier(2)]
			public int MultipleParameters(int @a, string @b)
			{
				if (this.Expectations.handlers2 is not null)
				{
					foreach (var @handler in this.Expectations.handlers2)
					{
						if (@handler.@a.IsValid(@a!) &&
							@handler.@b.IsValid(@b!))
						{
							@handler.CallCount++;
							var @result = @handler.Callback is not null ?
								@handler.Callback(@a!, @b!) : @handler.ReturnValue;
							return @result!;
						}
					}

					this.Expectations.WasExceptionThrown = true;
					throw new global::Rocks.Exceptions.ExpectationException(
						$"""
						No handlers match for {this.GetType().GetMemberDescription(2)}
							a: {@a.FormatValue()}
							b: {@b.FormatValue()}
						""");
				}

				this.Expectations.WasExceptionThrown = true;
				throw new global::Rocks.Exceptions.ExpectationException(
					$"""
					No handlers were found for {this.GetType().GetMemberDescription(2)}
						a: {@a.FormatValue()}
						b: {@b.FormatValue()}
					""");
			}

			public int GetAndSetData
			{
				[global::Rocks.MemberIdentifier(3)]
				get
				{
					if (this.Expectations.handlers3 is not null)
					{
						var @handler = this.Expectations.handlers3.First;
						@handler.CallCount++;
						var @result = @handler.Callback is not null ?
							@handler.Callback() : @handler.ReturnValue;
						return @result!;
					}

					this.Expectations.WasExceptionThrown = true;
					throw new global::Rocks.Exceptions.ExpectationException(
						$"""
						No handlers match for {this.GetType().GetMemberDescription(3)}
						""");
				}
				[global::Rocks.MemberIdentifier(4)]
				set
				{
					if (this.Expectations.handlers4 is not null)
					{
						var @foundMatch = false;
						foreach (var @handler in this.Expectations.handlers4)
						{
							if (@handler.value.IsValid(value!))
							{
								@handler.CallCount++;
								@foundMatch = true;
								@handler.Callback?.Invoke(value!);
								break;
							}
						}

						if (!@foundMatch)
						{
							this.Expectations.WasExceptionThrown = true;
							throw new global::Rocks.Exceptions.ExpectationException(
								$"""
								No handlers match for {this.GetType().GetMemberDescription(4)}
									value: {@value.FormatValue()}
								""");
						}
					}
					else
					{
						this.Expectations.WasExceptionThrown = true;
						throw new global::Rocks.Exceptions.ExpectationException(
							$"""
							No handlers were found for {this.GetType().GetMemberDescription(4)}
								value: {@value.FormatValue()}
							""");
					}
				}
			}

			public int this[int @a, string @b]
			{
				[global::Rocks.MemberIdentifier(5)]
				get
				{
					if (this.Expectations.handlers5 is not null)
					{
						foreach (var @handler in this.Expectations.handlers5)
						{
							if (@handler.@a.IsValid(@a!) &&
								@handler.@b.IsValid(@b!))
							{
								@handler.CallCount++;
								var @result = @handler.Callback is not null ?
									@handler.Callback(@a!, @b!) : @handler.ReturnValue;
								return @result!;
							}
						}

						this.Expectations.WasExceptionThrown = true;
						throw new global::Rocks.Exceptions.ExpectationException(
							$"""
							No handlers match for {this.GetType().GetMemberDescription(5)}
								a: {@a.FormatValue()}
								b: {@b.FormatValue()}
							""");
					}

					this.Expectations.WasExceptionThrown = true;
					throw new global::Rocks.Exceptions.ExpectationException(
						$"""
						No handlers were found for {this.GetType().GetMemberDescription(5)}
							a: {@a.FormatValue()}
							b: {@b.FormatValue()}
						""");
				}
				[global::Rocks.MemberIdentifier(6)]
				set
				{
					if (this.Expectations.handlers6 is not null)
					{
						foreach (var @handler in this.Expectations.handlers6)
						{
							if (@handler.@a.IsValid(@a!) &&
								@handler.@b.IsValid(@b!) &&
								@handler.@value.IsValid(@value!))
							{
								@handler.CallCount++;
								@handler.Callback?.Invoke(@a!, @b!, @value!);
								return;
							}
						}

						this.Expectations.WasExceptionThrown = true;
						throw new global::Rocks.Exceptions.ExpectationException(
							$"""
							No handlers match for {this.GetType().GetMemberDescription(6)}
								a: {@a.FormatValue()}
								b: {@b.FormatValue()}
								value: {@value.FormatValue()}
							""");
					}

					this.Expectations.WasExceptionThrown = true;
					throw new global::Rocks.Exceptions.ExpectationException(
						$"""
						No handlers were found for {this.GetType().GetMemberDescription(6)}
							a: {@a.FormatValue()}
							b: {@b.FormatValue()}
							value: {@value.FormatValue()}
						""");
				}
			}

			private global::Rocks.Experimental.IInterfaceCreateExpectations Expectations { get; }
		}

		public IInterfaceCreateExpectations() { }

		internal global::Rocks.Experimental.IInterfaceMethodReturn Instance()
		{
			if (!this.WasInstanceInvoked)
			{
				this.WasInstanceInvoked = true;
				var @mock = new Mock(this);
				this.MockType = @mock.GetType();
				return @mock;
			}
			else
			{
				throw new global::Rocks.Exceptions.NewMockInstanceException("Can only create a new mock once.");
			}
		}

		internal static class Adornments
		{
			public interface IAdornmentsForIInterface<TAdornments>
				: global::Rocks.IAdornments<TAdornments>
				where TAdornments : IAdornmentsForIInterface<TAdornments>
			{ }

			public sealed class AdornmentsForHandler0
				: global::Rocks.Adornments<AdornmentsForHandler0, global::Rocks.Experimental.IInterfaceCreateExpectations.Handler0, global::System.Func<int>, int>, IAdornmentsForIInterface<AdornmentsForHandler0>
			{
				public AdornmentsForHandler0(global::Rocks.Experimental.IInterfaceCreateExpectations.Handler0 handler)
					: base(handler) { }
			}
			public sealed class AdornmentsForHandler1
				: global::Rocks.Adornments<AdornmentsForHandler1, global::Rocks.Experimental.IInterfaceCreateExpectations.Handler1, global::System.Func<int, int>, int>, IAdornmentsForIInterface<AdornmentsForHandler1>
			{
				public AdornmentsForHandler1(global::Rocks.Experimental.IInterfaceCreateExpectations.Handler1 handler)
					: base(handler) { }
			}
			public sealed class AdornmentsForHandler2
				: global::Rocks.Adornments<AdornmentsForHandler2, global::Rocks.Experimental.IInterfaceCreateExpectations.Handler2, global::System.Func<int, string, int>, int>, IAdornmentsForIInterface<AdornmentsForHandler2>
			{
				public AdornmentsForHandler2(global::Rocks.Experimental.IInterfaceCreateExpectations.Handler2 handler)
					: base(handler) { }
			}
			public sealed class AdornmentsForHandler3
				: global::Rocks.Adornments<AdornmentsForHandler3, global::Rocks.Experimental.IInterfaceCreateExpectations.Handler3, global::System.Func<int>, int>, IAdornmentsForIInterface<AdornmentsForHandler3>
			{
				public AdornmentsForHandler3(global::Rocks.Experimental.IInterfaceCreateExpectations.Handler3 handler)
					: base(handler) { }
			}
			public sealed class AdornmentsForHandler4
				: global::Rocks.Adornments<AdornmentsForHandler4, global::Rocks.Experimental.IInterfaceCreateExpectations.Handler4, global::System.Action<int>>, IAdornmentsForIInterface<AdornmentsForHandler4>
			{
				public AdornmentsForHandler4(global::Rocks.Experimental.IInterfaceCreateExpectations.Handler4 handler)
					: base(handler) { }
			}
			public sealed class AdornmentsForHandler5
				: global::Rocks.Adornments<AdornmentsForHandler5, global::Rocks.Experimental.IInterfaceCreateExpectations.Handler5, global::System.Func<int, string, int>, int>, IAdornmentsForIInterface<AdornmentsForHandler5>
			{
				public AdornmentsForHandler5(global::Rocks.Experimental.IInterfaceCreateExpectations.Handler5 handler)
					: base(handler) { }
			}
			public sealed class AdornmentsForHandler6
				: global::Rocks.Adornments<AdornmentsForHandler6, global::Rocks.Experimental.IInterfaceCreateExpectations.Handler6, global::System.Action<int, string, int>>, IAdornmentsForIInterface<AdornmentsForHandler6>
			{
				public AdornmentsForHandler6(global::Rocks.Experimental.IInterfaceCreateExpectations.Handler6 handler)
					: base(handler) { }
			}
		}
	}
}

#pragma warning restore CS8618
#pragma warning restore CS8633
#pragma warning restore CS8714
#pragma warning restore CS8775